# Large 3D Trajectory MoE Configuration
# High-capacity model for complex 3D trajectory patterns

model:
  n_layers: 8
  input_dim: 3      # x, y, z coordinates
  target_dim: 3     # predict x, y, z positions  
  pool: "none"      # No pooling - sequence-to-sequence
  
  block:
    use_rms_norm: true
    
    attn:
      n_heads: 16
      attn_dropout: 0.1
      resid_dropout: 0.1
      bias: true
      causal: true
      use_rope: true
      rope_max_seq_len: 512
      
    moe:
      d_model: 1024
      
      router:
        n_experts: 32
        k: 4
        router_type: "topk"
        temperature: 1.0
        use_rms_norm: true
        load_balance_weight: 0.15
        
      expert:
        expert_type: "ffn"
        d_model: 1024
        d_hidden: 2048
        activation: "gelu"
        dropout: 0.1
        init: "scaled_xavier"

training:
  batch_size: 16      # Smaller batch size for larger model
  learning_rate: 0.0005
  max_steps: 50000
  warmup_steps: 2000
  weight_decay: 0.01
  gradient_clip_norm: 1.0
  
  # Learning rate schedule
  lr_schedule: "cosine"
  min_learning_rate: 0.00005
  
  # Evaluation
  eval_interval: 1000
  eval_steps: 200
  save_interval: 5000
  
  # MoE specific
  aux_loss_weight: 0.15
  load_balance_weight: 0.15

dataset:
  sequence_length: 128    # Longer context for complex patterns
  prediction_length: 32   # Predict more steps
  sampling_rate: 100.0    # Higher sampling rate
  noise_std: 0.01         # Less noise for cleaner learning
  
  # Trajectory type distribution
  helical_weight: 0.2
  orbital_weight: 0.2
  lissajous_weight: 0.2
  lorenz_weight: 0.2
  robotic_weight: 0.2

logging:
  project: "trajectory_3d_moe"
  run_name: "large_3d_moe"
  log_interval: 100
  save_visualizations: true
  
output:
  base_dir: "outputs/trajectory_3d"
  experiment_name: "large_3d_moe"